### PR TITLE
Feature: Realtime-UI | Config keybind, unit speed KPH or MPH

### PR DESCRIPTION
**Pull request by NRTnarathip**
Feature:
Realtime Update UI
set keybind toggle UI such as f10 or any key
set player can toggle UI?
set unit speed KPH,MPH

optimize little

### CODE REVIEW

**Comment by NRTnarathip** [comment]
If this patch is merged, I will continue to release the patch.
The next patch will have features.
Command:
    set unit speed,toggle HUD

**Comment by kasuganosoras** [comment]
Any screenshots for preview? Thanks

**Comment by NRTnarathip** [comment]
I suggest that you try loading the script I forked, since it has a performance loop engine, I suggest you give it a try.

**Comment by NRTnarathip** [comment]
https://github.com/NRTnarathip/fh4speed
download branch "master"

**Comment by NRTnarathip** [comment]
Or you don't have a server fivem executable? if not
I'll make a short vdo review soon.

**Comment by NRTnarathip** [comment]
https://www.youtube.com/watch?v=R95MDIYP6OY
branch "path-1" last my version

**Comment by kasuganosoras** [comment]
hi, I see you using the ESX event in the `client.lua`, I will merge it to `dev` branch first, thank you.

**Pull request merged**
