### PR TITLE
Path 1

### PR DESCRIPTION
**Pull request by NRTnarathip**

### CODE REVIEW

**Comment by NRTnarathip** [comment]
it just update path 1
just add feature command
-set unit display KPH,MPH
-toggle HUD

**Comment by kasuganosoras** [comment]
Hi, I update a new commit in dev branch, now the unit will follow your game profile, so you don't need to change it manually now.

**Comment by NRTnarathip** [comment]
Does that mean you don't want to update this path-1?
I am confused 😅

**Comment by NRTnarathip** [comment]
Oh, I read the path, I understand.

**Pull request closed without merging**
